name: Basic Build CI

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build-noetic:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
      image: ros:noetic-perception
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: rviz_aerial_image
      - name: Checkout tas_proj repo
        uses: actions/checkout@v2
        with:
          repository: UniBwTAS/tas_proj
          path: tas_proj
      - name: Checkout ogre_primitives repo
        uses: actions/checkout@v2
        with:
          repository: UniBwTAS/ogre_primitives
          path: ogre_primitives
      - name: Prepare ROS
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y python3-osrf-pycommon
          sudo apt-get install -y python3-catkin-pkg
          sudo apt-get install -y python3-catkin-tools
          source /opt/ros/$ROS_DISTRO/setup.bash
      - name: Create catkin workspace
        run: |
          mkdir ~/catkin_ws
          ln -s $GITHUB_WORKSPACE ~/catkin_ws/src
      - name: Install ROS packages with rosdep
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          rosdep update
          cd ~/catkin_ws
          rosdep install --from-paths src --ignore-src -r -y
      - name: catkin build
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          cd ~/catkin_ws
          catkin build --no-status
          source devel/setup.bash
